<?php
namespace Database\Seeders;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsTableSeeder extends Seeder
{
    public function run(){
        $products = $this->getProducts();
        foreach($products as $product){
            Product::updateOrCreate(['slug' => $product['slug']],$product);
        }
    }
    private function getProducts(){
        return [
            ['name' => '7-(Diethylamino)coumarin-3-carboxylic acid','slug' => 'PRD310202467197','catalog_number' => 'KMA0159','cas_number' => "323578-37-1",'price' => 50,'image' => "/assets/images/products/KMA0159.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '(3S)-3-amino-2-hydroxy-5-methylhexanoic acid HCl salt','slug' => 'PRD310202467271','catalog_number' => 'KMA0162','cas_number' => "323578-37-2",'price' => 50,'image' => "/assets/images/products/KMA0162.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'Fmoc-gamma-abu-oh','slug' => 'PRD310202467577','catalog_number' => 'KMA0176','cas_number' => "323578-37-3",'price' => 50,'image' => "/assets/images/products/KMA0176.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '2,5-bis((tert-butoxycarbonyl)(2-cyanoethyl)amino)pentanoic acid','slug' => 'PRD310202467597','catalog_number' => 'KMA0181','cas_number' => "323578-37-4",'price' => 50,'image' => "/assets/images/products/KMA0181.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '(2-bromoacetyl)glycine','slug' => 'PRD310202467517','catalog_number' => 'KMA0194','cas_number' => "323578-37-5",'price' => 50,'image' => "/assets/images/products/KMA0194.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '2,5-Dioxopyrrolidin-1-yl 7-hydroxy-2-oxo-2H-chromene-3-carboxylate','slug' => 'PRD310202461597','catalog_number' => 'KMA0197','cas_number' => "323578-37-6",'price' => 50,'image' => "/assets/images/products/KMA0197.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],

            ['name' => 'N-(3-Formylphenyl)acetamide','slug' => 'PRD310202467997','catalog_number' => 'KMA0135','cas_number' => "323578-33-1",'price' => 50,'image' => "/assets/images/products/KMA0135.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '3-methyl-1H-indazole-5-carbaldehyde','slug' => 'PRD310202463597','catalog_number' => 'KMA0133','cas_number' => "323578-33-2",'price' => 50,'image' => "/assets/images/products/KMA0133.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '2-Quinolinecarboxaldehyde','slug' => 'PRD310202469597','catalog_number' => 'KMA0113','cas_number' => "323578-33-3",'price' => 50,'image' => "/assets/images/products/KMA0113.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '21-dexaldehyde','slug' => 'PRD310202463547','catalog_number' => 'KMA0103','cas_number' => "323578-33-4",'price' => 50,'image' => "/assets/images/products/KMA0103.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '4- (Pyridin- 2- yl) benzaldehyde','slug' => 'PRD310202465197','catalog_number' => 'KMA0064','cas_number' => "323578-33-5",'price' => 50,'image' => "/assets/images/products/KMA0064.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'N-(3-Aminopropyl) maleimide trifluoroacetate salt','slug' => 'PRD310202465971','catalog_number' => 'KMA0065','cas_number' => "323578-33-6",'price' => 50,'image' => "/assets/images/products/KMA0065.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            
            ['name' => 'N-(3-Aminopropyl) maleimide trifluoroacetate salt','slug' => 'PRD310202417597','catalog_number' => 'KMA0202','cas_number' => "323578-34-1",'price' => 50,'image' => "/assets/images/products/KMA0202.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '6-(Boc-Amino)picoline','slug' => 'PRD310202427597','catalog_number' => 'KMA0200','cas_number' => "323578-34-2",'price' => 50,'image' => "/assets/images/products/KMA0200.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '2-(Tritylthio)ethanamine','slug' => 'PRD310202437597','catalog_number' => 'KMA0201','cas_number' => "323578-34-3",'price' => 50,'image' => "/assets/images/products/KMA0201.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '4-(Boc-Amino)picoline','slug' => 'PRD310202447597','catalog_number' => 'KMA0202','cas_number' => "323578-34-4",'price' => 50,'image' => "/assets/images/products/KMA0202-2.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '5-(Boc-Amino)picoline','slug' => 'PRD310202457597','catalog_number' => 'KMA0199','cas_number' => "323578-34-5",'price' => 50,'image' => "/assets/images/products/KMA0199.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'N1,N4-dibenzyl spermine','slug' => 'PRD310202477597','catalog_number' => 'KMA0193','cas_number' => "323578-34-6",'price' => 50,'image' => "/assets/images/products/KMA0193.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            
            ['name' => 'tert-butyl (2-bromoacetyl)glycinate','slug' => 'PRD310202497597','catalog_number' => 'KMA0195','cas_number' => "323578-35-1",'price' => 50,'image' => "/assets/images/products/KMA0195.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '(2-bromoacetyl)glycine','slug' => 'PRD310202486597','catalog_number' => 'KMA0194','cas_number' => "323578-35-2",'price' => 50,'image' => "/assets/images/products/KMA0194.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => 'Batimastat','slug' => 'PRD310202419597','catalog_number' => 'KMA0174','cas_number' => "323578-35-3",'price' => 50,'image' => "/assets/images/products/KMA0174.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '12-bromoberberine TFA salt','slug' => 'PRD310202499597','catalog_number' => 'KMA0153','cas_number' => "323578-35-4",'price' => 50,'image' => "/assets/images/products/KMA0153.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '(4-Bromo-2-chlorophenyl) deuteriomethanol','slug' => 'PRD310202465597','catalog_number' => 'KMA0152','cas_number' => "323578-35-5",'price' => 50,'image' => "/assets/images/products/KMA0152.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
            ['name' => '1-Chloro-4-(4-pyridinylmethyl) phthalazine','slug' => 'PRD310202476597','catalog_number' => 'KMA0146','cas_number' => "323578-35-6",'price' => 50,'image' => "/assets/images/products/KMA0146.svg",'specifications' => '[{"label":"Purity","value":"95+%"},{"label":"Is Rare","value":"No"},{"label":"Ships In","value":"2-3 days"},{"label":"Smiles","value":"NO"},{"label":"Molecular Formula","value":"NO"},{"label":"Molecular Weigth","value":"208.26"}]','created_at' => date("Y-m-d H:i:s"),'updated_at' => date("Y-m-d H:i:s")],
        ];
    }
}